<div class="page-content">
    <div class="mb-4"><h4 class="mb-1">Productos</h4><p class="text-muted mb-0">Selecciona una categoría y completa los datos definidos para ella.</p></div>
    @canany(['crear-producto','editar-producto'])
    <div class="card"><div class="card-body"><h5>{{ $productId ? 'Editar producto' : 'Nuevo producto' }}</h5>
        <form wire:submit="save"><div class="row g-3">
            <div class="col-md-4"><label class="form-label">Categoría</label><select wire:model.live="category_id" class="form-select @error('category_id') is-invalid @enderror"><option value="">Selecciona una categoría...</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select>@error('category_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-5"><label class="form-label">Nombre del producto</label><input wire:model="name" placeholder="Ejemplo: Laptop Toshiba" class="form-control @error('name') is-invalid @enderror">@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-3"><label class="form-label">Código <small class="text-muted">(opcional)</small></label><input wire:model="code" placeholder="Automático" class="form-control @error('code') is-invalid @enderror">@error('code')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            @php($selectedCategory = $categories->firstWhere('id', (int) $category_id))
            @if($selectedCategory)
                @foreach($selectedCategory->attributes->where('scope','product') as $attribute)
                <div class="col-md-4"><label class="form-label">{{ $attribute->name }} @if($attribute->pivot->required)<span class="text-danger">*</span>@endif</label>@include('livewire.products.attribute-input',['model'=>'productValues.'.$attribute->id,'attribute'=>$attribute])@error('productValues.'.$attribute->id)<small class="text-danger">{{ $message }}</small>@enderror</div>
                @endforeach
                @php($variantAttributes = $selectedCategory->attributes->where('scope','variant'))
                @php($unitAttribute = $selectedCategory->attributes->firstWhere('scope','unit'))
                <div class="col-12"><hr><div class="d-flex justify-content-between align-items-center"><div><h6 class="mb-1">{{ $variantAttributes->isNotEmpty() ? 'Variantes' : 'Identificación' }}</h6><small class="text-muted">{{ $variantAttributes->isNotEmpty() ? 'Una fila por talla, color o presentación.' : 'Datos únicos de este producto.' }}</small></div>@if($variantAttributes->isNotEmpty())<button type="button" wire:click="addVariant" class="btn btn-sm btn-outline-primary">+ Agregar variante</button>@endif</div>
                    @foreach($variants as $index => $variant)<div class="border rounded p-3 mt-2"><div class="row g-3">
                        @if($variantAttributes->isNotEmpty())<div class="col-md-3"><label class="form-label">Código / SKU <small class="text-muted">(opcional)</small></label><input wire:model="variants.{{ $index }}.sku" placeholder="Automático" class="form-control @error('variants.'.$index.'.sku') is-invalid @enderror">@error('variants.'.$index.'.sku')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>@endif
                        @foreach($variantAttributes as $attribute)<div class="col-md-3"><label class="form-label">{{ $attribute->name }} @if($attribute->pivot->required)<span class="text-danger">*</span>@endif</label>@include('livewire.products.attribute-input',['model'=>'variants.'.$index.'.values.'.$attribute->id,'attribute'=>$attribute])@error('variants.'.$index.'.values.'.$attribute->id)<small class="text-danger">{{ $message }}</small>@enderror</div>@endforeach
                        @if($unitAttribute)<div class="col-12"><label class="form-label">{{ $unitAttribute->name }} @if($unitAttribute->pivot->required)<span class="text-danger">*</span>@endif</label><textarea wire:model="variants.{{ $index }}.serials" rows="3" class="form-control @error('variants.'.$index.'.serials') is-invalid @enderror" placeholder="Uno por línea. Ejemplo: SN-001"></textarea><small class="text-muted">Cada identificador debe ser único en todo el sistema.</small>@error('variants.'.$index.'.serials')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>@endif
                        @if($variantAttributes->isNotEmpty())<div class="col-12 text-end"><button type="button" wire:click="removeVariant({{ $index }})" class="btn btn-sm btn-outline-danger" @disabled(count($variants) === 1)>Quitar variante</button></div>@endif
                    </div></div>@endforeach
                </div>
                <div class="col-12"><button class="btn btn-primary px-4">Guardar producto</button>@if($productId)<button type="button" wire:click="resetForm" class="btn btn-light">Cancelar</button>@endif</div>
            @else<div class="col-12"><div class="alert alert-light border mb-0">Selecciona una categoría para mostrar sus atributos.</div></div>@endif
        </div></form>
    </div></div>
    @endcanany
    <div class="card"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">Productos registrados</h5><input wire:model.live.debounce.300ms="searchTerm" class="form-control" style="max-width:360px" placeholder="Buscar producto..."></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Producto</th><th>Categoría</th><th>Datos</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>@forelse($products as $product)<tr><td><strong>{{ $product->name }}</strong><br><small class="text-muted">{{ $product->code }}</small></td><td>{{ $product->category->name }}</td><td>@foreach($product->attributeValues as $value)@if(filled($value->value))<span class="badge bg-light text-dark me-1">{{ $value->value }}</span>@endif @endforeach @if($product->variants->where('status',true)->count()>1)<span class="badge bg-info">{{ $product->variants->where('status',true)->count() }} variantes</span>@endif @if($product->tracking_type==='serialized')<span class="badge bg-primary">Serializado</span>@endif</td><td><span class="badge bg-{{ $product->status ? 'success' : 'secondary' }}">{{ $product->status ? 'Activo' : 'Inactivo' }}</span></td><td class="text-end">@can('editar-producto')<button wire:click="edit({{ $product->id }})" class="btn btn-sm btn-outline-primary"><i class="bx bx-edit"></i></button>@endcan @can('eliminar-producto')<button wire:click="toggle({{ $product->id }})" class="btn btn-sm btn-outline-{{ $product->status ? 'danger' : 'success' }}"><i class="bx bx-power-off"></i></button>@endcan</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">No hay productos registrados.</td></tr>@endforelse</tbody></table></div>{{ $products->links() }}</div></div>
</div>
