<div class="page-content">
    <div class="mb-4"><h4 class="mb-1">Paso 1 y 2: Categorías y sus atributos</h4><p class="text-muted mb-0">Primero crea una categoría. Después selecciónala para agregar los datos que pedirán sus productos.</p></div>

    <div class="card"><div class="card-body">
        <div class="d-flex align-items-center mb-3"><span class="badge rounded-pill bg-primary me-2">1</span><h5 class="mb-0">Crear categoría</h5></div>
        @canany(['crear-categoria','editar-categoria'])<form wire:submit="saveCategory"><div class="row g-3 align-items-end">
            <div class="col-md-4"><label class="form-label">Nombre de la categoría</label><input wire:model="name" placeholder="Ejemplo: Activo" class="form-control @error('name') is-invalid @enderror">@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-3"><label class="form-label">Código corto <small class="text-muted">(opcional)</small></label><input wire:model="code" placeholder="Automático: ACT" class="form-control @error('code') is-invalid @enderror">@error('code')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-3"><label class="form-label">Descripción <small class="text-muted">(opcional)</small></label><input wire:model="description" class="form-control"></div>
            <div class="col-md-2 d-flex gap-2"><button class="btn btn-primary flex-grow-1">{{ $categoryId ? 'Actualizar' : 'Crear' }}</button>@if($categoryId)<button type="button" wire:click="resetCategory" class="btn btn-light">×</button>@endif</div>
        </div></form>@endcanany
        <div class="row g-2 mt-3">@forelse($categories as $category)<div class="col-md-4"><div class="border rounded p-3 h-100 {{ $selectedCategoryId == $category->id ? 'border-primary bg-light' : '' }}"><div class="d-flex justify-content-between"><div><strong>{{ $category->name }}</strong><div class="small text-muted">{{ $category->code }} · {{ $category->products_count }} productos</div></div><span class="badge bg-{{ $category->status ? 'success' : 'secondary' }}">{{ $category->status ? 'Activa' : 'Inactiva' }}</span></div><div class="mt-3 d-flex gap-2"><button wire:click="selectCategory({{ $category->id }})" class="btn btn-sm btn-primary">Gestionar atributos</button>@can('editar-categoria')<button wire:click="editCategory({{ $category->id }})" class="btn btn-sm btn-outline-secondary"><i class="bx bx-edit"></i></button>@endcan</div></div></div>@empty<div class="col-12 text-center text-muted py-3">Crea tu primera categoría para continuar.</div>@endforelse</div>
    </div></div>

    @if($selectedCategory)
    <div class="card border-primary"><div class="card-body">
        <div class="d-flex align-items-center mb-1"><span class="badge rounded-pill bg-primary me-2">2</span><h5 class="mb-0">Atributos de “{{ $selectedCategory->name }}”</h5></div>
        <p class="text-muted">¿Qué datos quieres pedir al registrar un producto de esta categoría?</p>
        @can('gestionar-atributos')<form wire:submit="saveAttribute"><div class="row g-3 align-items-end">
            <div class="col-md-3"><label class="form-label">Nombre del dato</label><input wire:model="attributeName" placeholder="Ejemplo: Marca" class="form-control @error('attributeName') is-invalid @enderror">@error('attributeName')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-2"><label class="form-label">Tipo de respuesta</label><select wire:model.live="attributeType" class="form-select"><option value="text">Texto</option><option value="number">Número</option><option value="select">Elegir de una lista</option><option value="date">Fecha</option><option value="boolean">Sí / No</option></select></div>
            @if($attributeType === 'select')<div class="col-md-3"><label class="form-label">Opciones</label><input wire:model="attributeOptions" placeholder="7, 8, 9, 10" class="form-control"></div>@endif
            <div class="col-md-3"><label class="form-label">¿Cómo se utiliza?</label><select wire:model="attributeScope" class="form-select @error('attributeScope') is-invalid @enderror"><option value="product">Dato general del producto</option><option value="variant">Variante, por ejemplo talla o color</option><option value="unit">Identificador único, por ejemplo número de serie</option></select>@error('attributeScope')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-2"><label class="form-check mb-2"><input wire:model="attributeRequired" type="checkbox" class="form-check-input"> Obligatorio</label><button class="btn btn-primary w-100">{{ $attributeId ? 'Actualizar' : 'Agregar atributo' }}</button></div>
        </div></form>@endcan
        <div class="table-responsive mt-4"><table class="table align-middle"><thead><tr><th>Atributo</th><th>Respuesta</th><th>Uso</th><th>Obligatorio</th><th></th></tr></thead><tbody>@forelse($selectedCategory->attributes as $a)<tr><td><strong>{{ $a->name }}</strong></td><td>{{ ['text'=>'Texto','number'=>'Número','select'=>'Lista','date'=>'Fecha','boolean'=>'Sí / No'][$a->type] }}</td><td>{{ match($a->scope) { 'variant' => 'Variantes (talla/color)', 'unit' => 'Identificador único por unidad', default => 'Dato del producto' } }}</td><td>{{ $a->pivot->required ? 'Sí' : 'No' }}</td><td class="text-end">@can('gestionar-atributos')<button wire:click="editAttribute({{ $a->id }})" class="btn btn-sm btn-outline-primary"><i class="bx bx-edit"></i></button><button wire:click="removeAttribute({{ $a->id }})" wire:confirm="¿Quitar este atributo de la categoría?" class="btn btn-sm btn-outline-danger"><i class="bx bx-trash"></i></button>@endcan</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-3">Agrega Marca, Modelo y Número de serie, por ejemplo.</td></tr>@endforelse</tbody></table></div>
        <div class="alert alert-info mb-0"><i class="bx bx-info-circle"></i> Cuando termines, abre <a href="{{ route('products') }}" class="alert-link">Productos</a> para registrar tus productos.</div>
    </div></div>
    @endif
</div>
